### ISSUE TITLE
Hardness of blocks

### ISSUE THREAD

**Issue by hanakocz** [OpenModularTurretsTeam/OpenModularPassiveDefense#11]
Hi,
this is mostly feature request.
While we have instant mining of blocks via right-click empty hand, and while those blocks are unminable by normal means, can you please consider making them all really hard to break? Because it is so often that one missclicks, visually breaks the block, but it is still here....invisible. Sometimes this (not really) breaked block just won't reappear again, it will stay removed (even after server restart etc). Just because one swang his sword too near the fence.

It would be really useful if all those blocks can have way higher hardness (so it would take you for example 20 seconds to break), so those glitches are out of question. Also this would help against typical permission workaround known also with land-protections, that if you break those blocks that can be broken so fast, you can actually right-click the stuff behind the wall, just before the blocks reappear. 

This would be really apreciated.

**Comment by Keridos** [comment]
This is a bug, not a feature request :). Gonna take a look at that
