### ISSUE TITLE
Config Spam.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [OpenModularTurretsTeam/OpenModularPassiveDefense#14]
i noticed a day or so ago that the "recipes" folder in the config folder is building up duplicate recipes.... a lot of them.
it seems every time the game is launched it creates new "alt" versions of the recipes.
all the passive defence recipes seem to be affected, they are as such:
"fence_0_alt.json" 
"fence_0_alt_alt.json"
"fence_0_alt_alt_alt.json"
and it adds a new one with an extra "_alt" each time, just deleted the folder with:
"fence_0_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt_alt.json"

using MC 1.12.2
Forge-1.12.2-14.23.1.2554

**Comment by MokahTGS** [comment]
Yes, this is getting odd and annoying.  Can this please be changed or fixed.

**Comment by 1skandar** [comment]
Yeah, this will, eventually, cause problems thanks to overly long file names. You can manually clean this up, but it can be a bit frustrating for modpack devs.

**Comment by AlexIIL** [comment]
From the looks of it they are using a json recipe export library that was only meant to be ran once - not every launch.

**Comment by TheQKnight** [comment]
can we have a fix for this? I am a MP dev and I'm about to smash my pc to bits with this issue

**Comment by sandalle** [comment]
The simple work-around I applied to my modpack was to add this (*nix) code to my startup script before invoking the Minecraft server jar.
```
[[ -d config/recipes ]] && rm -rf config/recipes/
```

**Comment by LemADEC** [comment]
Already fixed in 2c7b3426f27ef8620061f450e3af07ad54a2ea36 ?

**Comment by AlexIIL** [comment]
@LemADEC yes, that commit by @Keridos fixed the issue but didn't reference this issue so it's just stayed open. This issue (and my PR) can be closed.
