### ISSUE TITLE
Server crush on load chank with opmd blocks

### ISSUE THREAD

**Issue by prokopiy** [OpenModularTurretsTeam/OpenModularPassiveDefense#18]
[crash-2018-05-16_19.03.18-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/files/2013331/crash-2018-05-16_19.03.18-server.txt)

[crash-2018-05-17_18.21.40-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/files/2013797/crash-2018-05-17_18.21.40-server.txt)

**Comment by Keridos** [comment]
Guessing that is because of our onload function, gonna take a look at this.

**Comment by FriendlyGamer** [comment]
I never even known such a interesting mod exists, however does this crash on native 1.12.2 Forge servers? Or is this bug only happening on Sponge as the crashes are referring to? I am asking this because I wish to deploy this on my 1.12.2 Forge server.

**Comment by LemADEC** [comment]
Any update on a fix @Keridos ?

**Comment by Keridos** [comment]
Try the new version, probably forgot this issue existed.

**Comment by LemADEC** [comment]
fixed in be2bd53ac6c26ddb37fe639706092d88c3c5bc92
