### ISSUE TITLE
[1.12.2] Existing world corruption/load issue after updating OM mods

### ISSUE THREAD

**Issue by GamertechAU** [OpenModularTurretsTeam/OpenModularPassiveDefense#25]
Loading my test worlds after updating to
OMLib: 3.1.0-233
OMPD: 3.1.0-55
OpenModularTurrets: 3.1.0-336

Worlds with no OM blocks in them load correctly, as do worlds with turrets but no OMPD hardened blocks. Worlds with OMPD blocks already placed however are corrupted and either get stuck on loading or crash with the below log.

Crash log: https://pastebin.com/nP6wHr8T

Reverting OM mod versions to previous release still causes the problem worlds to get stuck on loading, so something's happened to corrupt the OMPD blocks.

Placing OMPD blocks after the update seems to work as normal.

**Comment by Keridos** [comment]
On curseforge should be a new build soon. 8769448f54451ee842a67fa6bbf398e576b9182d has a few fixes that might fix this, but this is kind of hard to see since the stacktrace does not mention any of OMs mods source at all.

**Comment by Keridos** [comment]
https://jenkins.ironhide.de/job/OMTTeam/job/OMPD-1.12/lastSuccessfulBuild/artifact/build/libs/ompd-1.12.2-3.1.0-57.jar

**Comment by GamertechAU** [comment]
Updated to -60 and tested again. Locked up and generated the same changelog. Last section of the debug file below spamming:
`[Server thread/WARN] [net.minecraft.tileentity.TileEntity]: Skipping BlockEntity with id minecraft:ompd_owned_block`
before generating the same crashlog and getting stuck on Building Terrain.

https://pastebin.com/4MVPhznX

**Comment by Keridos** [comment]
From which version did you patch? This tile entity is not ingame since quite a while. Weird that it still tries to read it. You could theoretically enable removeErroringTileEntities in the forge config if it still exists.

/edit: found the issue, should work now.

**Comment by GamertechAU** [comment]
I'll test the update out in a bit thanks mate. But for info, it was 3.0.0-36. The last beta released before the overhaul started.

**Comment by GamertechAU** [comment]
It's still crashing my main world but I think I've narrowed down the cause.

It's seems that the old hardened blocks are conflicting with a YABBA barrel that they're stored in and causing a ticking entity crash.

The debug now shows:
`[Server thread/INFO] [ompd]: Fixed TE from minecraft:ompd_owned_block to ompd:ompd_owned_block`
instead of the ticking entity errors it was showing before, but it's also added 
```
[Server thread/WARN] [net.minecraft.util.datafix.walkers.BlockEntityTag]: Unable to resolve BlockEntity for ItemInstance: yabba:item_barrel
[Server thread/WARN] [net.minecraft.util.datafix.walkers.BlockEntityTag]: Unable to resolve BlockEntity for ItemInstance: yabba:item_barrel
[Server thread/WARN] [net.minecraft.util.datafix.walkers.BlockEntityTag]: Unable to resolve BlockEntity for ItemInstance: yabba:item_barrel
[Server thread/WARN] [net.minecraft.util.datafix.walkers.BlockEntityTag]: Unable to resolve BlockEntity for ItemInstance: yabba:item_barrel
```

Debug Section: https://pastebin.com/MLkrRScQ
Crashlog: https://pastebin.com/dxYgq2VR

**Comment by Keridos** [comment]
That is not my mods fault, contact the YABBA dev for that.

And stored items do not have any BlockEntity. Those are just created in case you deploy blocks with tile entities linked to them.
