### ISSUE TITLE
Open Modular Passive Defense requires wrong version of OMLib

### ISSUE THREAD

**Issue by AveoCross** [OpenModularTurretsTeam/OpenModularPassiveDefense#30]
When having latest OMLib (omlib-1.12.2-3.2.0-256.jar), OMPD throws dependency error:
Mod ompd (Open Modular Passive Defense) requires [omlib@[3.1.4-249,3.1.99-9999)]

**Comment by AveoCross** [comment]
Fixed in latest release!

**Comment by Desoroxxx** [comment]
Where is the latest release?
