### ISSUE TITLE
Incompatibility with OMLIB requring different version than Open Modular Turrets

### ISSUE THREAD

**Issue by CorneliusCornbread** [OpenModularTurretsTeam/OpenModularPassiveDefense#32]
OMPD requires OMLib 3.20 where OMT requires 3.15

**Comment by Keridos** [comment]
Which versions of the mods are you using?

**Comment by CorneliusCornbread** [comment]
> Which versions of the mods are you using?

ompd-1.12.2-3.2.0-76.jar
openmodularturrets-1.12.2-3.1.14-382.jar

reverting ompd back to the latest "release" on Curseforge seems to have resolved the problem. It seems ATLauncher will download the latest release regardless of whether it's Alpha or not when updating
